language: go

go:
- "1.12.5"

env:
  global:
    - GO111MODULE=on

jobs:
  include:

    - stage: unit-test
      script:
      - make test
      - bash <(curl -s https://codecov.io/bash)

    - stage: publish-image
      if: type = push
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - export IMG=orkaproj/instance-manager:$TRAVIS_BRANCH
      - make docker-build
      - make docker-push
