language: go

go:
- 1.12.x

git:
  depth: 1

env:
  global:
    - GO111MODULE=on

install: skip

jobs:
  include:

    - stage: unit-test
      script:
      - go test -v -mod=vendor ./controllers/... -coverprofile coverage.txt
      - bash <(curl -s https://codecov.io/bash)

    - stage: publish-image
      if: type = push
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - export IMG=orkaproj/instance-manager:$TRAVIS_BRANCH
      - make docker-build
      - make docker-push
