apiVersion: instancemgr.orkaproj.io/v1alpha1
kind: InstanceGroup
metadata:
  name: hello-world
spec:
  provisioner: eks-cf
  strategy:
    type: crd
    crd:
      crdName: workflows
      statusJSONPath: .status.phase
      statusSuccessString: Succeeded
      statusErrorString: Failed
      concurrencyPolicy: Forbid
      spec: |
        apiVersion: argoproj.io/v1alpha1
        kind: Workflow
        metadata:
          generateName: hello-world-parameters-
        spec:
          entrypoint: whalesay
          arguments:
            parameters:
            - name: message
              value: hello world
          templates:
          - name: whalesay
            inputs:
              parameters:
              - name: message
            container:
              image: docker/whalesay
              command: [cowsay]
              args: ["{{`{{inputs.parameters.message}}`}}"]
  eks-cf:
    minSize: 1
    maxSize: 3
    configuration:
      bootstrapArguments: --register-with-taints=my-taint-key=my-taint-value:NoSchedule --node-labels=my-label=true
      keyPairName: my-key
      image: ami-089d3b6350c1769a6
      instanceType: m5.large
      volSize: 20
      clusterName: my-eks-cluster
      subnets:
      - subnet-1a2b3c4d
      - subnet-4d3c2b1a
      - subnet-0w9x8y7z
      securityGroups:
      - sg-q1w2e3r4t5y6u7i8
      tags:
        - key: mykey
          value: myvalue