---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Amazon EKS - Node Group Role'
Resources:
  NodeGroupRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: ec2.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      Policies:
        -
          PolicyName: "EKSBootstrapNodeGroupRole"
          PolicyDocument:
           Version: "2012-10-17"
           Statement:
             -
               Effect: "Allow"
               Action: "iam:*"
               Resource: "*"
             -
               Effect: "Allow"
               Action: "ec2:*"
               Resource: "*"
             -
               Effect: "Allow"
               Action: "cloudformation:*"
               Resource: "*"
             -
               Effect: "Allow"
               Action: "autoscaling:*"
               Resource: "*"
             -
               Effect: "Allow"
               Action: "eks:*"
               Resource: "*"
Outputs:
  NodeGroupRoleArn:
    Description: The ARN for the created node group service role
    Value: !GetAtt NodeGroupRole.Arn
  NodeGroupRoleName:
    Description: The name of the created node group service role
    Value: !Ref NodeGroupRole