apiVersion: instancemgr.keikoproj.io/v1alpha1
kind: InstanceGroup
metadata:
  name: naveen-test-with-iam-managed-policies
spec:
  eks-cf:
    configuration:
      clusterName: eks-kdev2-k8s
      image: ami-015288619490c53cd
      instanceType: m5.large
      keyPairName: eks-kdev2-k8s-keypair
      managedPolicies:
        - AmazonDocDBFullAccess
        - AmazonCloudDirectoryFullAccess
      securityGroups:
        - sg-08453b229abb4bf
        - sg-029965312626144
        - sg-0f68186cedee6d7
      subnets:
        - subnet-0e8277599681557
        - subnet-0ad16fed12136f1
        - subnet-08b86b32e34cf87
      tags:
        - key: k8s.io/cluster-autoscaler/enabled
          value: "true"
        - key: kubernetes.io/cluster/eks-kdev2-k8s
          value: owned
      volSize: 80
    maxSize: 2
    minSize: 1
  provisioner: eks-cf
  strategy:
    type: rollingUpdate