apiVersion: instancemgr.keikoproj.io/v1alpha1
kind: VerticalScalingPolicy
metadata:
  name: verticalscalingpolicy-sample
spec:
  instanceFamily: m5

  resources:
    requests:
      mem: 8Gi
      cpu: 2
    limits:
      mem: 64Gi
      cpu: 16
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: NodesCountUtilizationPercentage
        value: 100
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 300
      policies:
      - type: NodesCountUtilizationPercentage
        value: 20
        periodSeconds: 60
  scaleTargetsRef:
  - apiVersion: instancemgr.keikoproj.io/v1alpha1
    kind: InstanceGroup
    name: nodes
    namespace: instance-manager

