apiVersion: instancemgr.keikoproj.io/v1alpha1
kind: InstanceGroup
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: bdd-test-rolling
  namespace: instance-manager
spec:
  provisioner: eks-cf
  strategy:
    type: rollingUpdate
    rollingUpdate:
      maxBatchSize: 1
      minInstancesInService: 1
      minSuccessfulInstancesPercent: 100
      pauseTime: PT2M
  eks-cf:
    maxSize: 4
    minSize: 2
    configuration:
      bootstrapArguments: --register-with-taints=node-role.kubernetes.io/bdd-test=bdd-test:NoSchedule --node-labels=test=bdd-test-rolling
      clusterName: {{ .ClusterName }}
      subnets: {{range $element := .Subnets}}
        - {{$element}}
      {{ end }}
      keyPairName: {{ .KeyPairName }}
      vpcId: {{ .VpcID }}
      image: {{ .AmiID }}
      instanceType: t2.small
      volSize: 20
      securityGroups: {{range $element := .NodeSecurityGroups}}
        - {{$element}}
      {{ end }}
      tags:
        - key: mykey
          value: myvalue