apiVersion: instancemgr.keikoproj.io/v1alpha1
kind: InstanceGroup
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: bdd-test-crd
  namespace: instance-manager-bdd
spec:
  provisioner: eks
  strategy:
    type: crd
    crd:
      crdName: rollingupgrades
      statusJSONPath: .status.currentStatus
      statusSuccessString: completed
      statusFailureString: error
      spec: |
        apiVersion: upgrademgr.keikoproj.io/v1alpha1
        kind: RollingUpgrade
        metadata:
          name: rollup-nodes
          namespace: instance-manager
        spec:
          postDrainDelaySeconds: 10
          nodeIntervalSeconds: 30
          asgName: {{`{{ .InstanceGroup.Status.ActiveScalingGroupName }}`}}
  eks:
    maxSize: 4
    minSize: 2
    configuration:
      labels:
        test: bdd-test-crd
      taints:
      - key: node-role.kubernetes.io/bdd-test
        value: bdd-test
        effect: NoSchedule
      clusterName: {{ .ClusterName }}
      subnets: {{range $element := .Subnets}}
        - {{$element}}
      {{ end }}
      keyPairName: {{ .KeyPairName }}
      image: {{ .AmiID }}
      instanceType: t2.small
      volumes:
      - name: /dev/xvda
        type: gp2
        size: 30
      securityGroups: {{range $element := .NodeSecurityGroups}}
        - {{$element}}
      {{ end }}
      tags:
      - key: k8s-minion-manager
        value: use-spot
      metricsCollection:
      - all