apiVersion: instancemgr.orkaproj.io/v1alpha1
kind: InstanceGroup
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: bdd-test-crd
  namespace: instance-manager
spec:
  provisioner: eks-cf
  strategy:
    type: crd
    crd:
      crdName: rollingupgrades
      statusJSONPath: .status.currentStatus
      statusSuccessString: completed
      statusErrorString: error
      spec: |
        apiVersion: upgrademgr.orkaproj.io/v1alpha1
        kind: RollingUpgrade
        metadata:
          name: rollup-nodes
          namespace: instance-manager
        spec:
          postDrainDelaySeconds: 30
          nodeIntervalSeconds: 180
          region: {{`{{ .ControllerRegion }}`}}
          asgName: {{`{{ .InstanceGroup.Status.ActiveScalingGroupName }}`}}
  eks-cf:
    maxSize: 6
    minSize: 3
    configuration:
      bootstrapArguments: --register-with-taints=node-role.kubernetes.io/bdd-test=bdd-test:NoSchedule --node-labels=test-label.kubernetes.io/a-label=true
      clusterName: {{ .ClusterName }}
      subnets: {{ .Subnets }}
      keyPairName: {{ .KeyPairName }}
      vpcId: {{ .VpcID }}
      image: {{ .AmiID }}
      instanceType: m3.medium
      volSize: 20
      securityGroups: {{ .NodeSecurityGroups }}
      tags:
        - key: mykey
          value: myvalue