apiVersion: instancemgr.keikoproj.io/v1alpha1
kind: InstanceGroup
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: bdd-test-rolling
  namespace: instance-manager
spec:
  provisioner: eks
  strategy:
    type: rollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  eks:
    maxSize: 4
    minSize: 2
    configuration:
      labels:
        test: bdd-test-rolling
      taints:
      - key: node-role.kubernetes.io/bdd-test
         value: bdd-test
         effect: NoSchedule
      clusterName: {{ .ClusterName }}
      subnets: {{range $element := .Subnets}}
        - {{$element}}
      {{ end }}
      keyPairName: {{ .KeyPairName }}
      image: {{ .AmiID }}
      instanceType: t2.small
      volumes:
      - name: /dev/xvda
        type: gp2
        size: 30
      securityGroups: {{range $element := .NodeSecurityGroups}}
        - {{$element}}
      {{ end }}
      tags:
        - key: mykey
          value: myvalue